apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.podName}}
    service:  {{.Values.appName}}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service:  {{.Values.appName}}
