apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.podName}}
    service:  {{.Values.appName}}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web
    nodePort: 30030
  selector:
    service:  {{.Values.appName}}
